# Generated by Django 5.2.6 on 2025-10-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(choices=[('DEPORTES', 'Deportes'), ('LUCHAS', 'Luchas'), ('CARRERAS', 'Carreras'), ('ACCION', 'Acción'), ('AVENTURAS', 'Aventuras'), ('RPG', 'Rol (RPG)'), ('ESTRATEGIA', 'Estrategia'), ('SIMULACION', 'Simulación'), ('PUZZLE', 'Puzzle'), ('TERROR', 'Terror'), ('SHOOTER', 'Shooter'), ('PLATAFORMAS', 'Plataformas'), ('MUSICAL', 'Musical'), ('PARTY', 'Party'), ('SANDBOX', 'Sandbox'), ('MMO', 'MMO'), ('EDUCATIVO', 'Educativo'), ('OTROS', 'Otros')], max_length=30, unique=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
    ]
