# Generated by Django 5.2.6 on 2025-10-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PC', 'PC'), ('PLAYSTATION', 'PlayStation'), ('XBOX', 'Xbox'), ('NINTENDO', 'Nintendo')], max_length=20)),
            ],
            options={
                'db_table': 'plataformas',
            },
        ),
    ]
