# Generated by Django 5.2.6 on 2025-10-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
        ('plataformas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos_Plataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.juego')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformas.plataforma')),
            ],
            options={
                'db_table': 'juegos_plataformas',
                'unique_together': {('juego', 'plataforma')},
            },
        ),
    ]
