# Generated by Django 5.2.6 on 2025-10-04 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_juegos_plataformas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='juegos/')),
                ('url', models.URLField(blank=True, null=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.juego')),
            ],
        ),
    ]
