# Generated by Django 5.2.6 on 2025-10-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_fotos_juegos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fotos_juegos',
            table='fotos_juegos',
        ),
    ]
