# Generated by Django 5.2.6 on 2025-09-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelousuariomodificado',
            options={},
        ),
        migrations.AlterModelTable(
            name='modelousuariomodificado',
            table='usuarios',
        ),
    ]
